fzxiao233/Auto_Record_Matsuri

config.py
main.py
mirrativ.py
requirements.txt
youtube.py

修正M台录制后无法退出的问题

---

README.MD
mirrativ.py
tools.py
youtube.py

支持自动发布到百度云并分享

---

config.py
main.py
mirrativ.py
openrec.py
requirements.txt
tools.py
youtube.py

使用aiohttp替换了urllib

---

main.py
mirrativ.py
openrec.py
tools.py
twitcasting.py
youtube.py

现在下载模块不在阻塞监控

---

main.py
mirrativ.py
openrec.py
tools.py
twitcasting.py
youtube.py

Reverts fzxiao233/Auto_Record_Matsuri#42

Revert "现在下载模块不在阻塞监控"

---

twitcasting.py
video_process.py

修正T台模块：错用get_json

---

tools.py

迁移至mongodb

---

test/test_main.py
video_process.py

修正filename blocker

---

video_process.py

修正标题过长导致的报错

---

config.py
run.py
video_process.py

为未部署 mongodb 的用户提供兼容

---

tools.py

重构部分代码
Signed-off-by: fzxiao <fzxiao@Outlook.com>

为Requests部分添加异常处理，

---

test/test_main.py
video_process.py

Signed-off-by: fzxiao <fzxiao@Outlook.com>

修复emoji导致的无法上传

---

mirrativ.py
openrec.py
run.py
tools.py
twitcasting.py
youtube.py

修复逻辑错误导致的不断启动下载的问题

---

test/test_main.py
video_process.py
youtube.py

#75: add new youtube monitor method without api_key

---

video_process.py

fix after live end it still start new download

---

video_process.py

修复不合法的文件名引起的无法上传

---

youtube.py

修正youtube的重复检测

---

video_process.py

修改重名为添加时间戳

---

upload.py
users_map.py

加入user_map

---

youtube.py

修复了检测问题，改为通过IsLive 标签进行检测

---

daemon.py
tools.py
twitcasting.py
upload.py
video_process.py
youtube.py

修正了bot缺少的参数
